name: 'Read version with Build scripts'
description: 'Read the version of the assembly and retain'

runs:
  using: 'composite'
  steps:
    - name: 📥 Read version with Build scripts
      id: ver
      shell: bash
      run: |
        set -Eeuo pipefail
        nameBuild=$(./_run/scripts/sys.sh -n)
        versionBuild=$(./_run/scripts/sys.sh -v)

        echo "BUILD_NAME=$nameBuild"   >  build_env.txt
        echo "BUILD_VER=$versionBuild" >> build_env.txt

        echo "name=$nameBuild"   >> $GITHUB_OUTPUT
        echo "version=$versionBuild" >> $GITHUB_OUTPUT

        echo "✔️ Found version: $versionBuild (Package Name: $nameBuild)"