name: 'Setup GO with cache'
description: 'Setup GO and configure modules cache'
inputs:
  go-version:
    description: 'GO version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🔧 Install Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v5
      with:
        cache: true
        go-version: ${{ env.GO_VERSION }}

    - name: 🗂️ GO modules cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          "C:\\Users\\runneradmin\\go\\pkg\\mod"
        key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles(format('./go.mod')) }}
        restore-keys: ${{ runner.os }}-go