name: 'Initialization of all packages'
description: 'Initialize all the modules and generate files'

runs:
  using: 'composite'
  steps:
    - name: 📥 go mod tidy-all
      shell: bash
      run: ./_run/scripts/go_tidy_all.sh

    - name: 🛠️ go generate
      shell: bash
      env:
        GOFLAGS: -mod=mod
      run: |
        set -Eeuo pipefail
        mkdir -p target tmp
        go generate ./...